[phases.setup]
nixPkgs = ["python311", "chromium", "chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120 --log-level debug --access-logfile - --error-logfile -"
